### ISSUE TITLE
Ausführung eines interaktiven Level-Ruby Programms lässt sich nicht stoppen

### ISSUE THREAD

**Issue by JTiko** [lakrme/atom-levels#2]
Ich habe mir eine einfache echo-Prozedur geschrieben und aufgerufen:

```
def echo
  str = gets();
  puts(str);
end

echo();
```

Dann habe ich das Programm ausgeführt und wollte diese wieder stoppen, was allerdings nicht funktionierte. Wenn ich nach dem Stoppen noch versucht habe, etwas im Terminal einzugeben, gab es eine Fehlermeldung, dass der Socket geschlossen ist.

**Comment by lakrme** [comment]
Das Problem ist mir bekannt (siehe [hier](https://github.com/lakrme/atom-levels/blob/09a10a3029c2f066655a4eb476bbd5fab696a9e7/lib/execution-manager.coffee#L79-L83)). Die `kill`-Funktion terminiert leider nur den root-Prozess `sh`, nicht aber die Kindprozesse, d.h. der Ruby-Interpreter läuft weiter, es besteht aber keine Verbindung mehr. Im Interface tut sich beim Klick auf den Stop-Button auch nichts, da der Terminierungs-Event nie gefeuert wird (erst wenn man den Ruby-Interpreter-Prozess per Hand abschießt - dann erscheint auch wieder der Run-Button). 

Leider habe ich bisher noch keine gute Lösung dafür gefunden. Das selbe Problem besteht sogar auch bei einer analogen Atom-API-Funktion (siehe z.B. [hier](https://github.com/rgbkrk/atom-script/issues/453)) und ist da noch nicht gelöst worden. In der "finalen" Version des Plugins werde ich die Stop-Funktionalität sonst einfach wieder rausnehmen oder eine Fehlermeldung anzeigen.

**Comment by lakrme** [comment]
Ich hab jetzt eine Lösung unter Mac gefunden. Es wäre toll, wenn du testen könntest, ob das unter Ubuntu auch funktioniert. :-) Am besten mit dem gleichen Programm wie oben (mit nicht-terminierenden while-Schleifen, die in jeder Iteration was ausgeben habe ich gerade noch andere Probleme, die ich erstmal beheben muss).

Falls alles glatt läuft sollte der `Stop`-Button wieder zum `Run`-Button werden und im Terminal müsste wieder das `Levels>`-Prompt angezeigt werden.

**Comment by lakrme** [comment]
Lösung für Windows wurde nun auch erfolgreich getestet!

**Comment by JTiko** [comment]
Auf meinem Debian-System lässt sich die Ausführung des obigen Programms nun erfolgreich stoppen :-)

**Comment by lakrme** [comment]
Dann mach ich hier mal zu.
