### ISSUE TITLE
Anmerkungen und Fragen zum Layout

### ISSUE THREAD

**Issue by JTiko** [lakrme/atom-levels#3]
1. Gibt es irgendwie die Möglichkeit, den run-Button besser sichtbar zu plazieren bzw. diesen zu vergrößern? Ich finde, dass er bislang etwas untergeht.
2. Das Terminal überdeckt bei größeren Programmen weite Programmteile. Zwar kann man es einklappen, aber selbst dann werden noch 1-2 Zeilen verdeckt. Nur durch das Einfügen weiterer Leerzeilen im Editorfenster kann man diese Zeilen "sichtbar machen", was etwas unschön ist.
   Ist es ohne größeren Aufwand möglich, dass Terminal als separates Fenster zu realisieren bzw. alternativ das Overlay-Terminal frei verschiebbar zu machen (z.B. an rechten Bildschirmrand)?
3. Am rechten Rand des Terminals unterhalb des run-Buttons ist ein weiteres kleines Terminal zu sehen. Welchen Zweck erfüllt es?

**Comment by lakrme** [comment]
Moin,
1. Das ist sicherlich möglich
2. Dass das Terminal Teile des Programms überlappt ist mir noch garnicht aufgefallen - habe immer kleine Programme getestet. ;) Ich weiß allerdings auch schon woran es liegt: Um Elemente zum UI hinzuzufügen muss man sie in "atom-panel"-Custom-HTML-Elemente einbetten. Aus Gründen habe ich das Terminal absolut zu dem zugehörigen atom-panel-Element platziert, wodurch das eigentliche atom-panel-Element garkeinen Platz in Anspruch nimm, weil es keinen relativ positionierten Inhalt hat. Der von einem atom-panel-Element verbrauchte Platz wird allerdings "korrekt" von der Höhe des Editors abgezogen (so wie es z.B. auch bei der Standard-Statuszeile unten der Fall ist). Da muss ich die Positionierung also nur anpassen, dann sollte die Höhe des Terminal von der Höhe des Editorfensters abgezogen werden, d.h. wenn man nach ganz unten scrollt müsste die letzte Zeile dann immer über dem Terminal zu sehen sein.
3. Ein weiteres kleines Terminal? Ohje, das ist mir neu. Kannst du davon vielleicht einen Screenshot hochladen?

**Comment by JTiko** [comment]
Hier ein Screenshot von dem kleinen schmalen Terminal unten rechts (unterhalb des run-Buttons).
![terminal](https://cloud.githubusercontent.com/assets/5038161/9730951/4a1128ac-561a-11e5-8bbd-720e4a40f70a.png)

**Comment by lakrme** [comment]
Oha, dieses zweite Terminal sehe ich zum ersten Mal...

Kannst du vielleicht mal über die Developer Tools (bei mir _View > Developer > Toggle Developer Tools_) nachgucken, welches DOM-Element das da rechts ist? 

Speziell um welches Kindelement von dem `div.terminal-panel` es sich handelt:

![screen shot 2015-09-08 at 21 02 01](https://cloud.githubusercontent.com/assets/12169730/9744565/eb630f16-566c-11e5-934c-090380a9b09f.png)

Nochmal bzgl. 2.:
Das freie Positionieren des Terminals wäre schon etwas aufwändiger als die anderen Sachen. Ich werde erstmal das Problem mit der Überlappung beheben. Dann verschwindet zumindest kein Code mehr hinter dem Terminal. :-)

**Comment by lakrme** [comment]
Das Terminal sollte sich nun so verhalten wie die Atom Status Bar.

**Comment by JTiko** [comment]
Sehr schön, jetzt kann man auch bei längeren Programmen ohne Probleme den gesamten Code sehen :)

Was das zweite Termin betrifft, es scheint sich um folgendes DOM-Element zu handeln:

```
<div class="terminal" tabindex="0" is="space-pen-div" style="display: block; height: 320px; font-size: 12px; line-height: 16px;"> ... </div>
```

Hier auch nochmal ein Screenshot:
![terminal](https://cloud.githubusercontent.com/assets/5038161/9755588/7439825a-56d3-11e5-857f-d6d9a7073059.png)

**Comment by lakrme** [comment]
Das "zweite Terminal" sollte nun verschwunden sein. :-)

**Comment by JTiko** [comment]
Stimmt, das merkwürdige zweite Terminal ist nun nicht mehr da.
