### ISSUE TITLE
Level-Ruby Syntaxhighlighting

### ISSUE THREAD

**Issue by JTiko** [lakrme/atom-levels#4]
Auf Sprachlevel 2 werden viele Schlüsselwörter wie `if`, `then`, `else` oder auch `end` nicht korrekt hervorgehoben.
Auf den anderen Sprachleveln ist dies hingegen kein Problem.

**Comment by lakrme** [comment]
It's not a bug, it's a feature!

Das hab ich absichtlich gemacht um die Verwendung verschiedener Grammatik-Definitionen für die einzelnen Level zu testen. ;-) Man hat als Sprachentwickler bzgl. der Grammatiken 3 Optionen:
1. Man gibt gar keine Grammatik an, d.h. es ist kein grammar-Ordner notwendig und keine entsprechenden Angaben in der config - in diesem Fall wird eine leere Grammatik ohne Syntax-Highlighting für alle Level der Sprache verwendet (wie z.B. bei dem Haskell-Beispiel).
2. Man definiert eine "Default Grammar". Die Default Grammar wird für alle Level verwendet, für die keine eigene Grammatik definiert wurde (siehe 3.). Wenn man bzgl. des Syntax-Highlighting nicht zwischen Leveln unterscheiden möchte, genügt es die Default Grammar zu definieren. Dazu muss man vor der Installation in der config mit dem Schlüssel `defaultGrammar` den Pfad zu einer solchen Grammatik-Datei setzen.
3. Man definiert Grammatiken für einzelne Level innerhalb des `levels`-Arrays in der config. Diese haben dann eine höhere Priorität als die Default Grammar der Sprache (falls gesetzt). So kann man unterschiedliches Syntax-Highlighting für unterschiedliche Level definieren - z.B. bestimmte Schlüsselwörter hervorheben und andere nicht.

Das letzte wollte ich damit testen. Die Grammatiken sind nur zu Testzwecken dabei. Letztendlich muss der Sprachentwickler entscheiden, welche Grammatiken er benutzt.

**Comment by JTiko** [comment]
Alles klar, danke für die Erklärung ;)

Das sollte dann am besten auch noch im Wiki dokumentiert werden.

**Comment by lakrme** [comment]
Ist geschehen! Und zwar [hier](https://github.com/lakrme/atom-levels/wiki/Dokumentation-f%C3%BCr-Sprachentwickler#syntax-highlighting).
