### ISSUE TITLE
Programmablauf: Interaktive Programme mit Eingabeaufforderung

### ISSUE THREAD

**Issue by JTiko** [lakrme/atom-levels#6]
Wenn man ein interaktives Programm mit Eingabeaufforderung wie

```
def greet
  puts("What's your name:");
  name = gets();
  puts("Hi " + name);
end;

greet();
```

ausführt, dann erscheint die Eingabeaufforderung "What's your name:" erst nachdem der Nutzer etwas eingegeben hat.

**Comment by lakrme** [comment]
Hey,

das liegt glaube ich ebenfalls eher am (Line) Buffering des Ruby-Interpreters, worauf ich weder in der Executable noch im Plugin Einfluss habe. Ich schätze, dass dieses Problem behoben werden kann, indem der PrettyPrinter `$stdout.sync = true` vor jedes erzeugte Ruby-Programm schreibt (wie beim letzten Treffen von mir angesprochen). Im Level-Ruby-Programm kann man dies momentan leider nicht testen, da die Anweisung nicht vom Parser akzeptiert wird.

Ich lass hier mal offen bis klar ist, ob dass das Problem behebt.

**Comment by lakrme** [comment]
Wurde für das Ruby-Sprachpaket mit [diesem](https://github.com/lakrme/atom-levels-language-ruby/commit/d9de5ac3814d3d1e84b85b0bc8b96210a8b62086) Commit behoben.
